Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default 
      Tags: 
        - Key: Name
          Value: Codepipeline Demo

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: False
      VpcId: !Ref VPC
      Tags: 
      - Key: Name
        Value: Codepipeline Demo